import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '📚 Generated Documentation',
      items: [{type: 'autogenerated', dirName: 'generated'}],
    },
  ],
};

export default sidebars;
