import type {ReactNode} from 'react';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';

export default function Home(): ReactNode {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout title={siteConfig.title} description="AI-powered automatic documentation generator for VSCode">
      <main style={{fontFamily: "'Segoe UI', sans-serif"}}>

        {/* Hero */}
        <section style={{
          padding: '80px 40px',
          textAlign: 'center',
          background: 'white',
          borderBottom: '1px solid #eee',
        }}>
          <div style={{
            display: 'inline-block',
            background: '#f0fdf8',
            color: '#1aaa77',
            fontSize: '12px',
            fontWeight: 700,
            letterSpacing: '1.5px',
            textTransform: 'uppercase',
            padding: '6px 16px',
            borderRadius: '20px',
            marginBottom: '24px',
          }}>
            VSCode Extension
          </div>
          <h1 style={{
            fontSize: '48px',
            fontWeight: 800,
            color: '#111',
            marginBottom: '20px',
            lineHeight: 1.2,
          }}>
            Auto-Doc Agent
          </h1>
          <p style={{
            fontSize: '18px',
            color: '#666',
            maxWidth: '540px',
            margin: '0 auto 40px',
            lineHeight: 1.7,
          }}>
            Write code. Hover over any function. See documentation — automatically generated by AI.
          </p>
          <div style={{display: 'flex', gap: '12px', justifyContent: 'center', flexWrap: 'wrap'}}>
            <Link
              to="/intro"
              style={{
                padding: '14px 32px',
                background: '#2ecc99',
                color: 'white',
                borderRadius: '8px',
                fontWeight: 700,
                fontSize: '14px',
                textDecoration: 'none',
                letterSpacing: '0.5px',
              }}>
              Get Started
            </Link>
            <Link
              href="https://marketplace.visualstudio.com/items?itemName=JohnyJames.auto-doc-agent"
              style={{
                padding: '14px 32px',
                background: 'white',
                color: '#333',
                borderRadius: '8px',
                fontWeight: 700,
                fontSize: '14px',
                textDecoration: 'none',
                border: '1px solid #e0e0e0',
                letterSpacing: '0.5px',
              }}>
              Install Extension
            </Link>
          </div>
        </section>

        {/* Features */}
        <section style={{
          padding: '80px 40px',
          background: '#f7f8fa',
          borderBottom: '1px solid #eee',
        }}>
          <div style={{maxWidth: '900px', margin: '0 auto'}}>
            <h2 style={{
              textAlign: 'center',
              fontSize: '28px',
              fontWeight: 700,
              color: '#111',
              marginBottom: '48px',
            }}>
              Everything you need
            </h2>
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(3, 1fr)',
              gap: '24px',
            }}>
              {[
                {title: 'AI Generated', desc: 'Gemini AI reads your code and writes accurate, detailed documentation automatically.'},
                {title: 'Hover Tooltips', desc: 'Documentation appears instantly when you hover over any function in VSCode.'},
                {title: 'Multi-language', desc: 'Supports Python, TypeScript and JavaScript out of the box.'},
                {title: 'Redis Caching', desc: 'Already documented functions load instantly from cache — no repeated API calls.'},
                {title: 'Private Dashboard', desc: 'Browse all your documented functions organized by project and file.'},
                {title: 'Always Up-to-date', desc: 'Docs regenerate automatically whenever you change a function.'},
              ].map((f, i) => (
                <div key={i} style={{
                  background: 'white',
                  border: '1px solid #e8e8e8',
                  borderRadius: '10px',
                  padding: '24px',
                }}>
                  <h3 style={{fontSize: '15px', fontWeight: 700, color: '#111', marginBottom: '10px'}}>{f.title}</h3>
                  <p style={{fontSize: '14px', color: '#666', lineHeight: 1.7, margin: 0}}>{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How it works */}
        <section style={{padding: '80px 40px', background: 'white', borderBottom: '1px solid #eee'}}>
          <div style={{maxWidth: '600px', margin: '0 auto', textAlign: 'center'}}>
            <h2 style={{fontSize: '28px', fontWeight: 700, color: '#111', marginBottom: '48px'}}>
              How it works
            </h2>
            {[
              {step: '1', title: 'Install the extension', desc: 'Search Auto-Doc Agent in the VSCode Marketplace and install it.'},
              {step: '2', title: 'Get your API key', desc: 'Register at auto-doc-agent.onrender.com and copy your permanent API key.'},
              {step: '3', title: 'Add to settings', desc: 'Paste your API key into VSCode User Settings JSON and reload.'},
              {step: '4', title: 'Write code', desc: 'Write any function and hover over it to see AI-generated documentation.'},
            ].map((s, i) => (
              <div key={i} style={{display: 'flex', gap: '20px', marginBottom: '32px', textAlign: 'left'}}>
                <div style={{
                  width: '36px',
                  height: '36px',
                  background: '#f0fdf8',
                  border: '2px solid #2ecc99',
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontWeight: 800,
                  fontSize: '14px',
                  color: '#1aaa77',
                  flexShrink: 0,
                }}>
                  {s.step}
                </div>
                <div>
                  <h3 style={{fontSize: '15px', fontWeight: 700, color: '#111', marginBottom: '6px'}}>{s.title}</h3>
                  <p style={{fontSize: '14px', color: '#666', lineHeight: 1.7, margin: 0}}>{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section style={{
          padding: '80px 40px',
          background: '#f0fdf8',
          textAlign: 'center',
        }}>
          <h2 style={{fontSize: '28px', fontWeight: 700, color: '#111', marginBottom: '12px'}}>
            Ready to get started?
          </h2>
          <p style={{fontSize: '15px', color: '#666', marginBottom: '32px'}}>
            Free to use. No credit card required.
          </p>
          <Link
            href="https://auto-doc-agent.onrender.com"
            style={{
              padding: '14px 40px',
              background: '#2ecc99',
              color: 'white',
              borderRadius: '8px',
              fontWeight: 700,
              fontSize: '14px',
              textDecoration: 'none',
            }}>
            Create Free Account
          </Link>
        </section>

      </main>
    </Layout>
  );
}